# Site settings
author: Varun Vachhar
title: varun vachhar
email: varunvachhar@gmail.com
description: finder of new ways to confuse myself
baseurl: ""
url: http://varun.ca
twitter_username: winkerVSbecks
github_username:  winkerVSbecks
writing_desc: writing about JavaScript, CSS and reactive animations.

# Post settings
excerpt_separator: <!--more-->
permalink: /:title

# Build settings
markdown: kramdown
theme: minima
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock


# Custom vars
version: 1.0.0
github:
  repo: https://github.com/winkerVSbecks/varun.ca
