# Site settings
author: Varun Vachhar
title: Varun Vachhar
email: varunvachhar@gmail.com
description: I am a developer with a strong focus on design, interactivity and animation. Originally from New Delhi, I currently live in Toronto and work as the Director, UI Architecture at Rangle.io. In my spare time, I like to experiment with creative coding, making triangles and other playful experiences for the web.
baseurl: ''
url: https://varun.ca
twitter_username: winkerVSbecks
github_username: winkerVSbecks
writing_desc: writing about JavaScript, CSS and reactive animations.

# Post settings
permalink: /:title/

# Build settings
markdown: kramdown
theme: minima
highlighter: rouge

gems:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - yarn.lock
  - postcss.config.js
  - imagemin.js
  - package.json

# Custom vars
version: 1.0.0
github:
  repo: https://github.com/winkerVSbecks/varun.ca
